import React from 'react';

import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: { maxWidth: '1200px' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  title: { fontFamily: 'var(--font-heading)', fontSize: '24px', fontWeight: 600, margin: 0 },
  subtitle: { color: 'var(--text-secondary)', fontSize: '15px', marginTop: '2px' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: '16px' },
  card: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    boxShadow: 'var(--shadow-sm)',
    overflow: 'hidden',
  },
  cardHeader: {
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    cursor: 'pointer',
  },
  avatar: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: 'var(--accent-secondary)',
    color: '#FFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '20px',
    flexShrink: 0,
  },
  cardBody: { flex: 1, minWidth: 0 },
  docName: { fontSize: '16px', fontWeight: 600, marginBottom: '2px' },
  docSpec: { fontSize: '13px', color: 'var(--text-secondary)' },
  statusBadge: (status: string) => ({
    fontSize: '11px',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: '100px',
    background: status === 'Approved' ? '#ECFDF3' : status === 'Rejected' ? '#FEF3F2' : '#FEF7E6',
    color: status === 'Approved' ? '#027A48' : status === 'Rejected' ? '#D92D20' : '#F79009',
  }),
  contactRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    color: 'var(--text-secondary)',
    marginTop: '4px',
  },
  expandArea: {
    borderTop: '1px solid var(--border)',
    padding: '16px 20px',
    background: '#F8FAFC',
  },
  scheduleSection: { marginBottom: '12px' },
  scheduleTitle: { fontSize: '13px', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '8px', textTransform: 'uppercase' },
  slotGrid: { display: 'flex', flexWrap: 'wrap', gap: '6px' },
  slot: (filled: boolean, max: number) => ({
    padding: '6px 10px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 500,
    border: `1px solid ${filled >= max ? '#FECDCA' : '#E2E8F0'}`,
    background: filled >= max ? '#FEF3F2' : '#FFF',
    color: filled >= max ? 'var(--status-error)' : 'var(--text-primary)',
  }),
  actions: { display: 'flex', gap: '8px', marginTop: '12px' },
  editBtn: {
    display: 'flex', alignItems: 'center', gap: '6px',
    padding: '8px 14px', borderRadius: '8px', border: '1px solid var(--border)',
    background: '#FFF', fontWeight: 600, fontSize: '13px', cursor: 'pointer',
  },
  deleteBtn: {
    display: 'flex', alignItems: 'center', gap: '6px',
    padding: '8px 14px', borderRadius: '8px', border: '1px solid #FECDCA',
    background: '#FFF', color: 'var(--status-error)', fontWeight: 600, fontSize: '13px', cursor: 'pointer',
  },
  pagination: {
    display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '12px',
    marginTop: '24px', padding: '16px 0',
  },
  pageBtn: (disabled: boolean) => ({
    padding: '8px 16px', borderRadius: '8px', border: '1px solid var(--border)',
    background: disabled ? '#F2F4F7' : '#FFF', fontWeight: 600, fontSize: '14px',
    cursor: disabled ? 'not-allowed' : 'pointer', color: disabled ? 'var(--text-secondary)' : 'var(--text-primary)',
    opacity: disabled ? 0.5 : 1,
  }),
  pageInfo: { fontSize: '14px', color: 'var(--text-secondary)' },
  overlay: {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    background: 'rgba(16, 24, 40, 0.4)', display: 'flex',
    alignItems: 'center', justifyContent: 'center', zIndex: 200,
  },
  modal: {
    width: '500px', maxHeight: '90vh', overflowY: 'auto',
    padding: '32px', background: '#FFF', borderRadius: '16px',
  },
  modalHeader: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px',
  },
  modalTitle: { fontSize: '20px', fontWeight: 700 },
  label: { display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '6px' },
  input: {
    width: '100%', padding: '10px 14px', fontSize: '15px',
    border: '1px solid var(--border)', borderRadius: '8px', outline: 'none', marginBottom: '16px',
  },
  textarea: {
    width: '100%', padding: '10px 14px', fontSize: '15px',
    border: '1px solid var(--border)', borderRadius: '8px', outline: 'none',
    marginBottom: '16px', minHeight: '80px', resize: 'vertical',
  },
  errorMsg: {
    background: '#FEF3F2', color: 'var(--status-error)',
    padding: '10px 14px', borderRadius: '8px', fontSize: '14px',
    marginBottom: '16px', border: '1px solid #FECDCA',
  },
  modalActions: { display: 'flex', gap: '12px', justifyContent: 'flex-end', marginTop: '8px' },
  emptyState: { textAlign: 'center', padding: '60px 0', color: 'var(--text-secondary)' },
  detailLabel: { fontSize: '11px', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase' as const, letterSpacing: '0.5px' },
  detailValue: { fontSize: '14px', fontWeight: 500, color: 'var(--text-primary)', marginTop: '2px' },
  statsRow: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '16px', marginBottom: '24px' },
  statCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    padding: '18px 20px',
    boxShadow: 'var(--shadow-sm)',
  },
  statLabel: { fontSize: '12px', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase' as const, letterSpacing: '0.5px' },
  statValue: { fontSize: '28px', fontWeight: 700, color: 'var(--text-primary)', marginTop: '4px' },
  pendingSection: { marginBottom: '24px' },
  pendingTitle: { fontSize: '16px', fontWeight: 600, margin: 0 },
  pendingSubtitle: { fontSize: '13px', color: 'var(--text-secondary)', margin: '4px 0 12px' },
  approveBtn: {
    display: 'flex', alignItems: 'center', gap: '6px',
    padding: '8px 14px', borderRadius: '8px', border: 'none',
    background: '#027A48', color: '#FFF', fontWeight: 600, fontSize: '13px', cursor: 'pointer',
  },
  rejectBtn: {
    display: 'flex', alignItems: 'center', gap: '6px',
    padding: '8px 14px', borderRadius: '8px', border: '1px solid #FECDCA',
    background: '#FFF', color: 'var(--status-error)', fontWeight: 600, fontSize: '13px', cursor: 'pointer',
  },
  rejectReason: {
    fontSize: '13px', color: 'var(--status-error)',
    background: '#FEF3F2', border: '1px solid #FECDCA',
    padding: '10px 14px', borderRadius: '8px', marginBottom: '12px',
  },
  requestedAt: { fontSize: '12px', color: 'var(--text-secondary)' },
};
