import * as Linking from 'expo-linking';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { Share, Platform } from 'react-native';
import { Appointment } from '../store/slices/appointmentSlice';
import { formatEthiopianLocalTime } from './ethiopianDate';


/**
 * Format appointment data into a clean text string for sharing
 */
export const formatScheduleText = (appointments: Appointment[], dateLabel: string, isEthiopian?: boolean) => {
  let text = `📅 *BM Booking Schedule - ${dateLabel}*\n\n`;
  
  if (appointments.length === 0) {
    text += "No appointments scheduled for today.";
    return text;
  }

  appointments.forEach((apt, index) => {
    const time = isEthiopian ? formatEthiopianLocalTime(new Date(apt.dateTime)) : new Date(apt.dateTime).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    const patientName = apt.patient?.patientProfile?.fullName || 'Unknown Patient';
    const phone = apt.patient?.phone || 'N/A';
    
    text += `${index + 1}. [${time}] *${patientName}*\n`;
    text += `   📞 ${phone}\n`;
    if (apt.reason) text += `   📝 Issue: ${apt.reason}\n`;
    text += `\n`;
  });

  text += `Generated by BM Booking`;
  return text;
};

/**
 * Generate a CSV string from appointments
 */
export const generateCSV = (appointments: Appointment[]) => {
  let csv = 'Time,Patient Name,Phone,Issue,Status\n';
  
  appointments.forEach(apt => {
    const time = new Date(apt.dateTime).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    const patientName = apt.patient?.patientProfile?.fullName || 'Unknown Patient';
    const phone = apt.patient?.phone || 'N/A';
    const reason = (apt.reason || '').replace(/,/g, ';');
    
    csv += `"${time}","${patientName}","${phone}","${reason}","${apt.status}"\n`;
  });
  
  return csv;
};

/**
 * Share text via SMS
 */
export const shareViaSMS = (text: string) => {
  const url = `sms:?body=${encodeURIComponent(text)}`;
  Linking.openURL(url);
};

/**
 * Share text via WhatsApp
 */
export const shareViaWhatsApp = (text: string) => {
  const url = `whatsapp://send?text=${encodeURIComponent(text)}`;
  Linking.openURL(url).catch(() => {
    alert('WhatsApp is not installed');
  });
};

/**
 * Share text via Telegram
 */
export const shareViaTelegram = (text: string) => {
  const url = `tg://msg?text=${encodeURIComponent(text)}`;
  Linking.openURL(url).catch(() => {
    alert('Telegram is not installed');
  });
};

/**
 * Share content as a file (CSV)
 */
export const shareAsFile = async (content: string, filename: string) => {
  try {
    const fileUri = `${FileSystem.cacheDirectory}${filename}`;
    await FileSystem.writeAsStringAsync(fileUri, content);
    
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/csv',
        dialogTitle: 'Export Schedule',
        UTI: 'public.comma-separated-values-text'
      });
    } else {
      // Fallback to native share text if file sharing not available
      Share.share({ message: content });
    }
  } catch (error) {
    console.error('Export error:', error);
    alert('Failed to export file');
  }
};

/**
 * Generic Native Share
 */
export const shareNative = (text: string) => {
  Share.share({
    message: text,
    title: 'Patient Schedule'
  });
};
