export const DOCTORS_BY_CATEGORY: Record<
  string,
  {
    id: string;
    name: string;
    specialty: string;
    generalSpecialty: string;
    rating: string;
    reviews: string;
    hospital: string;
    experience: number;
  }[]
> = {
  Cardiology: [
    {
      id: "cardio-1",
      name: "Dr. Sarah Jenkins",
      specialty: "Cardiologist",
      generalSpecialty: "Cardiology",
      rating: "4.9",
      reviews: "120",
      hospital: "Heart Institute",
      experience: 12,
    },
    {
      id: "cardio-2",
      name: "Dr. Michael Chen",
      specialty: "Cardiologist",
      generalSpecialty: "Cardiology",
      rating: "4.8",
      reviews: "85",
      hospital: "City General",
      experience: 8,
    },
    {
      id: "cardio-3",
      name: "Dr. Elena Rodriguez",
      specialty: "Interventional Cardiologist",
      generalSpecialty: "Cardiology",
      rating: "5.0",
      reviews: "210",
      hospital: "St. Marys Medical",
      experience: 15,

    },
    {
      id: "cardio-4",
      name: "Dr. Amina Patel",
      specialty: "Heart Failure Specialist",
      generalSpecialty: "Cardiology",
      rating: "4.7",
      reviews: "102",
      hospital: "Ascent Heart Center",
      experience: 10,
    },
    {
      id: "cardio-5",
      name: "Dr. James Bryant",
      specialty: "Cardiologist",
      generalSpecialty: "Cardiology",
      rating: "4.8",
      reviews: "78",
      hospital: "Northside Clinic",
      experience: 9,
    },
    {
      id: "cardio-6",
      name: "Dr. Priya Sharma",
      specialty: "Electrophysiologist",
      generalSpecialty: "Cardiology",
      rating: "4.9",
      reviews: "134",
      hospital: "MetroCardio",
      experience: 11,
    },
    {
      id: "cardio-7",
      name: "Dr. Lucas Morgan",
      specialty: "Cardiology Consultant",
      generalSpecialty: "Cardiology",
      rating: "4.7",
      reviews: "97",
      hospital: "Oakwood Medical",
      experience: 7,
    },
    {
      id: "cardio-8",
      name: "Dr. Sophia Blake",
      specialty: "Pediatric Cardiologist",
      generalSpecialty: "Cardiology",
      rating: "4.8",
      reviews: "110",
      hospital: "Children's Heart Hospital",
      experience: 13,
    },
    {
      id: "cardio-9",
      name: "Dr. Noah Kim",
      specialty: "Interventional Cardiologist",
      generalSpecialty: "Cardiology",
      rating: "4.6",
      reviews: "65",
      hospital: "Riverbend Health",
      experience: 6,
    },
    {
      id: "cardio-10",
      name: "Dr. Grace Liu",
      specialty: "Cardiology Specialist",
      generalSpecialty: "Cardiology",
      rating: "4.9",
      reviews: "143",
      hospital: "Lakeside Medical",
      experience: 14,
    },
  ],
  Dental: [
    {
      id: "dental-1",
      name: "Dr. Matthew Ford",
      specialty: "Dentist",
      generalSpecialty: "Dental",
      rating: "4.8",
      reviews: "90",
      hospital: "Bright Smile Clinic",
      experience: 8,
    },
    {
      id: "dental-2",
      name: "Dr. Nina Gomez",
      specialty: "Orthodontist",
      generalSpecialty: "Dental",
      rating: "4.7",
      reviews: "73",
      hospital: "SmileCare Dental",
      experience: 10,
    },
    {
      id: "dental-3",
      name: "Dr. Ava Grant",
      specialty: "Endodontist",
      generalSpecialty: "Dental",
      rating: "4.9",
      reviews: "125",
      hospital: "Pearl Dental Center",
      experience: 12,
    },
    {
      id: "dental-4",
      name: "Dr. Omar Hassan",
      specialty: "Periodontist",
      generalSpecialty: "Dental",
      rating: "4.6",
      reviews: "54",
      hospital: "Gum Health Clinic",
      experience: 9,
    },
    {
      id: "dental-5",
      name: "Dr. Zoe Martins",
      specialty: "Pediatric Dentist",
      generalSpecialty: "Dental",
      rating: "4.8",
      reviews: "88",
      hospital: "Little Teeth Care",
      experience: 7,
    },
    {
      id: "dental-6",
      name: "Dr. Ethan Miller",
      specialty: "Cosmetic Dentist",
      generalSpecialty: "Dental",
      rating: "4.9",
      reviews: "103",
      hospital: "Urban Dental",
      experience: 11,
    },
    {
      id: "dental-7",
      name: "Dr. Priya Raman",
      specialty: "Orthodontist",
      generalSpecialty: "Dental",
      rating: "4.7",
      reviews: "69",
      hospital: "Align Dental",
      experience: 6,
    },
    {
      id: "dental-8",
      name: "Dr. Caleb Torres",
      specialty: "Oral Surgeon",
      generalSpecialty: "Dental",
      rating: "4.8",
      reviews: "82",
      hospital: "Sage Surgical Center",
      experience: 13,
    },
    {
      id: "dental-9",
      name: "Dr. Lila Brooks",
      specialty: "Dentist",
      generalSpecialty: "Dental",
      rating: "4.6",
      reviews: "58",
      hospital: "Family Dental Care",
      experience: 5,
    },
    {
      id: "dental-10",
      name: "Dr. Isabella Reed",
      specialty: "Dental Hygienist",
      generalSpecialty: "Dental",
      rating: "4.9",
      reviews: "130",
      hospital: "Pearl Dental Center",
      experience: 8,
    },
  ],
  General: [
    {
      id: "general-1",
      name: "Dr. Adam Lewis",
      specialty: "General Practitioner",
      generalSpecialty: "General",
      rating: "4.7",
      reviews: "67",
      hospital: "Community Health",
      experience: 6,
    },
    {
      id: "general-2",
      name: "Dr. Maya Patel",
      specialty: "Family Physician",
      generalSpecialty: "General",
      rating: "4.8",
      reviews: "102",
      hospital: "Wellness Center",
      experience: 9,
    },
    {
      id: "general-3",
      name: "Dr. Henry Diaz",
      specialty: "Primary Care Doctor",
      generalSpecialty: "General",
      rating: "4.9",
      reviews: "118",
      hospital: "Greenwood Clinic",
      experience: 12,
    },
    {
      id: "general-4",
      name: "Dr. Leah Wilson",
      specialty: "General Practitioner",
      generalSpecialty: "General",
      rating: "4.6",
      reviews: "74",
      hospital: "Valley Medical",
      experience: 7,
    },
    {
      id: "general-5",
      name: "Dr. Omar Khan",
      specialty: "Family Doctor",
      generalSpecialty: "General",
      rating: "4.7",
      reviews: "80",
      hospital: "City Family Care",
      experience: 8,
    },
    {
      id: "general-6",
      name: "Dr. Sophia Nguyen",
      specialty: "Internal Medicine",
      generalSpecialty: "General",
      rating: "4.8",
      reviews: "93",
      hospital: "Eastside Health",
      experience: 11,
    },
    {
      id: "general-7",
      name: "Dr. Ethan Park",
      specialty: "General Medicine",
      generalSpecialty: "General",
      rating: "4.7",
      reviews: "89",
      hospital: "Bridgeview Medical",
      experience: 10,
    },
    {
      id: "general-8",
      name: "Dr. Hannah Reed",
      specialty: "Primary Care",
      generalSpecialty: "General",
      rating: "4.9",
      reviews: "111",
      hospital: "Harbor Clinic",
      experience: 13,
    },
    {
      id: "general-9",
      name: "Dr. Leo Foster",
      specialty: "General Practitioner",
      generalSpecialty: "General",
      rating: "4.6",
      reviews: "64",
      hospital: "Sunrise Medical",
      experience: 5,
    },
    {
      id: "general-10",
      name: "Dr. Olivia Scott",
      specialty: "Family Physician",
      generalSpecialty: "General",
      rating: "4.8",
      reviews: "96",
      hospital: "Cedar Health",
      experience: 9,
    },
  ],
  Neurology: [
    {
      id: "neuro-1",
      name: "Dr. Rachel Mills",
      specialty: "Neurologist",
      generalSpecialty: "Neurology",
      rating: "4.9",
      reviews: "132",
      hospital: "NeuroCenter",
      experience: 14,
    },
    {
      id: "neuro-2",
      name: "Dr. Daniel Price",
      specialty: "Neurosurgeon",
      generalSpecialty: "Neurology",
      rating: "4.8",
      reviews: "97",
      hospital: "Brain & Spine Institute",
      experience: 16,
    },
    {
      id: "neuro-3",
      name: "Dr. Priya Desai",
      specialty: "Neurologist",
      generalSpecialty: "Neurology",
      rating: "4.7",
      reviews: "81",
      hospital: "Summit Neurology",
      experience: 11,
    },
    {
      id: "neuro-4",
      name: "Dr. Jason Wright",
      specialty: "Stroke Specialist",
      generalSpecialty: "Neurology",
      rating: "4.8",
      reviews: "88",
      hospital: "Crestview Hospital",
      experience: 13,

    },
    {
      id: "neuro-5",
      name: "Dr. Leila Ahmad",
      specialty: "Epileptologist",
      generalSpecialty: "Neurology",
      rating: "4.9",
      reviews: "106",
      hospital: "NeuroCare",
      experience: 12,
    },
    {
      id: "neuro-6",
      name: "Dr. Kyle Brown",
      specialty: "Pediatric Neurologist",
      generalSpecialty: "Neurology",
      rating: "4.7",
      reviews: "72",
      hospital: "Children's Neuro Center",
      experience: 10,
    },
    {
      id: "neuro-7",
      name: "Dr. Vera Kim",
      specialty: "Movement Disorder Specialist",
      generalSpecialty: "Neurology",
      rating: "4.8",
      reviews: "90",
      hospital: "Metro Neuroscience",
      experience: 15,
    },
    {
      id: "neuro-8",
      name: "Dr. Owen Lee",
      specialty: "Neurologist",
      generalSpecialty: "Neurology",
      rating: "4.6",
      reviews: "63",
      hospital: "Parkview Medical",
      experience: 8,
    },
    {
      id: "neuro-9",
      name: "Dr. Erin Chase",
      specialty: "Neurosurgeon",
      generalSpecialty: "Neurology",
      rating: "4.7",
      reviews: "79",
      hospital: "Origin Health",
      experience: 9,
    },
    {
      id: "neuro-10",
      name: "Dr. Melissa Carter",
      specialty: "Neuro-oncologist",
      generalSpecialty: "Neurology",
      rating: "4.9",
      reviews: "113",
      hospital: "City Neuro Institute",
      experience: 17,
    },
  ],
  Pediatrics: [
    {
      id: "peds-1",
      name: "Dr. Emily Hart",
      specialty: "Pediatrician",
      generalSpecialty: "Pediatrics",
      rating: "4.9",
      reviews: "145",
      hospital: "Children's Health Center",
      experience: 11,
    },
    {
      id: "peds-2",
      name: "Dr. Ryan Chen",
      specialty: "Pediatrician",
      generalSpecialty: "Pediatrics",
      rating: "4.8",
      reviews: "109",
      hospital: "Bright Kids Clinic",
      experience: 9,
    },
    {
      id: "peds-3",
      name: "Dr. Sophie Green",
      specialty: "Neonatologist",
      generalSpecialty: "Pediatrics",
      rating: "4.7",
      reviews: "83",
      hospital: "Little Stars Hospital",
      experience: 13,
    },
    {
      id: "peds-4",
      name: "Dr. Aaron Patel",
      specialty: "Pediatric Specialist",
      generalSpecialty: "Pediatrics",
      rating: "4.8",
      reviews: "96",
      hospital: "Sunrise Pediatrics",
      experience: 8,
    },
    {
      id: "peds-5",
      name: "Dr. Chloe Diaz",
      specialty: "Pediatrician",
      generalSpecialty: "Pediatrics",
      rating: "4.9",
      reviews: "121",
      hospital: "Northside Kids Care",
      experience: 10,
    },
    {
      id: "peds-6",
      name: "Dr. Benjamin Ross",
      specialty: "Pediatrician",
      generalSpecialty: "Pediatrics",
      rating: "4.7",
      reviews: "78",
      hospital: "Community Children's",
      experience: 7,
    },
    {
      id: "peds-7",
      name: "Dr. Alice Kim",
      specialty: "Adolescent Medicine",
      generalSpecialty: "Pediatrics",
      rating: "4.8",
      reviews: "92",
      hospital: "Harbor Pediatrics",
      experience: 12,
    },
    {
      id: "peds-8",
      name: "Dr. Owen Smith",
      specialty: "Pediatric Pulmonologist",
      generalSpecialty: "Pediatrics",
      rating: "4.6",
      reviews: "67",
      hospital: "Lakeside Kids Clinic",
      experience: 14,
    },
    {
      id: "peds-9",
      name: "Dr. Maya Jordan",
      specialty: "Pediatric Cardiologist",
      generalSpecialty: "Pediatrics",
      rating: "4.8",
      reviews: "88",
      hospital: "Children's Heart Center",
      experience: 15,
    },
    {
      id: "peds-10",
      name: "Dr. Lucas Reed",
      specialty: "Pediatric Neurologist",
      generalSpecialty: "Pediatrics",
      rating: "4.9",
      reviews: "101",
      hospital: "Kids Neuro Center",
      experience: 16,
    },
  ],
  Surgery: [
    {
      id: "surg-1",
      name: "Dr. Olivia Bell",
      specialty: "General Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.8",
      reviews: "98",
      hospital: "City Surgical Center",
      experience: 12,
    },
    {
      id: "surg-2",
      name: "Dr. Noah White",
      specialty: "Orthopedic Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.9",
      reviews: "116",
      hospital: "Precision Surgery",
      experience: 14,
    },
    {
      id: "surg-3",
      name: "Dr. Grace Wilson",
      specialty: "Neurosurgeon",
      generalSpecialty: "Surgery",
      rating: "4.7",
      reviews: "73",
      hospital: "Spine & Brain Institute",
      experience: 16,
    },
    {
      id: "surg-4",
      name: "Dr. Jackson Patel",
      specialty: "Plastic Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.8",
      reviews: "84",
      hospital: "Renew Surgery Center",
      experience: 10,
    },
    {
      id: "surg-5",
      name: "Dr. Hannah Lee",
      specialty: "Cardiothoracic Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.9",
      reviews: "109",
      hospital: "Heart & Lung Hospital",
      experience: 18,
    },
    {
      id: "surg-6",
      name: "Dr. Ethan Murphy",
      specialty: "Vascular Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.7",
      reviews: "76",
      hospital: "Riverbend Surgical",
      experience: 11,

    },
    {
      id: "surg-7",
      name: "Dr. Ava Carter",
      specialty: "Trauma Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.8",
      reviews: "88",
      hospital: "Bay Medical Center",
      experience: 13,
    },
    {
      id: "surg-8",
      name: "Dr. Maxine Scott",
      specialty: "Orthopedic Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.6",
      reviews: "65",
      hospital: "Peak Orthopedics",
      experience: 9,
    },
    {
      id: "surg-9",
      name: "Dr. Lucas Park",
      specialty: "Pediatric Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.7",
      reviews: "79",
      hospital: "Children's Surgical Center",
      experience: 15,
    },
    {
      id: "surg-10",
      name: "Dr. Isabella Moore",
      specialty: "General Surgeon",
      generalSpecialty: "Surgery",
      rating: "4.9",
      reviews: "118",
      hospital: "Summit Surgery",
      experience: 17,
    },
  ],
};

export const TAB_DOCTORS = [
  {
    id: "1",
    name: "Dr. Sarah Jenkins",
    specialty: "Cardiologist",
    generalSpecialty: "Cardiology",
    rating: "4.9",
    reviews: "120",
    hospital: "Heart Institute",
    experience: 12,
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    specialty: "Cardiologist",
    generalSpecialty: "Cardiology",
    rating: "4.8",
    reviews: "85",
    hospital: "City General",
    experience: 8,
  },
  {
    id: "3",
    name: "Dr. Elena Rodriguez",
    specialty: "Cardiologist",
    generalSpecialty: "Cardiology",
    rating: "5.0",
    reviews: "210",
    hospital: "St. Marys Medical",
    experience: 15,
  },
  {
    id: "4",
    name: "Dr. James Wilson",
    specialty: "Neurologist",
    generalSpecialty: "Neurology",
    rating: "4.7",
    reviews: "95",
    hospital: "Brain Center",
    experience: 10,
  },
  {
    id: "5",
    name: "Dr. Lisa Park",
    specialty: "Neurologist",
    generalSpecialty: "Neurology",
    rating: "4.6",
    reviews: "78",
    hospital: "Neuro Clinic",
    experience: 9,
  },
  {
    id: "6",
    name: "Dr. Robert Kim",
    specialty: "Dermatologist",
    generalSpecialty: "Dental",
    rating: "4.8",
    reviews: "150",
    hospital: "Skin Care Center",
    experience: 11,
  },
  {
    id: "7",
    name: "Dr. Maria Garcia",
    specialty: "Pediatrician",
    generalSpecialty: "Pediatrics",
    rating: "4.9",
    reviews: "200",
    hospital: "Children's Hospital",
    experience: 14,
  },
  {
    id: "8",
    name: "Dr. David Lee",
    specialty: "Orthopedic Surgeon",
    generalSpecialty: "Surgery",
    rating: "4.5",
    reviews: "110",
    hospital: "Bone & Joint Clinic",
    experience: 13,
  },
];

// Helper function to get all doctors as a flat array
export const getAllDoctors = () => {
  const allDoctors: any[] = [];
  Object.values(DOCTORS_BY_CATEGORY).forEach((category) => {
    allDoctors.push(...category);
  });
  return allDoctors;
};

// Helper function to find a doctor by ID
export const findDoctorById = (id: string) => {
  // First check in DOCTORS_BY_CATEGORY
  for (const category in DOCTORS_BY_CATEGORY) {
    const found = DOCTORS_BY_CATEGORY[category].find((doc) => doc.id === id);
    if (found) return found;
  }

  // Then check in TAB_DOCTORS
  return TAB_DOCTORS.find((doc) => doc.id === id);
};

// Get featured doctors (top rated)
export const getFeaturedDoctors = (count: number = 3) => {
  const allDoctors = getAllDoctors();
  return allDoctors
    .sort((a, b) => parseFloat(b.rating) - parseFloat(a.rating))
    .slice(0, count);
};
