export const MEDICAL_SPECIALIZATIONS = [
  "Allergy and Immunology",
  "Anesthesiology",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Child and Adolescent Psychiatry",
  "Clinical Neurophysiology",
  "Colon and Rectal Surgery",
  "Critical Care Medicine",
  "Dermatology",
  "Diagnostic Radiology",
  "Emergency Medicine",
  "Endocrinology, Diabetes and Metabolism",
  "Family Medicine",
  "Gastroenterology",
  "General Surgery",
  "Geriatric Medicine",
  "Gynecologic Oncology",
  "Hematology",
  "Hospice and Palliative Medicine",
  "Infectious Disease",
  "Internal Medicine",
  "Medical Genetics",
  "Medical Oncology",
  "Neonatal-Perinatal Medicine",
  "Nephrology",
  "Neurological Surgery",
  "Neurology",
  "Neuroradiology",
  "Nuclear Medicine",
  "Obstetrics and Gynecology",
  "Occupational Medicine",
  "Ophthalmology",
  "Orthopaedic Surgery",
  "Otolaryngology (ENT)",
  "Pain Medicine",
  "Pathology",
  "Pediatric Cardiology",
  "Pediatric Surgery",
  "Pediatrics",
  "Physical Medicine and Rehabilitation",
  "Plastic Surgery",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonary Disease",
  "Radiation Oncology",
  "Reproductive Endocrinology and Infertility",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Thoracic Surgery",
  "Urology",
  "Vascular Surgery"
];
