import type { CSSProperties } from 'react';

export const adminPageStyles: Record<string, CSSProperties> = {
  page: {
    padding: '36px',
    maxWidth: '960px',
    margin: '0 auto',
    flex: 1,
    overflowY: 'auto',
  },
  pageWide: {
    padding: '36px',
    maxWidth: '1100px',
    margin: '0 auto',
    flex: 1,
    overflowY: 'auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '32px',
    gap: '32px',
  },
  title: {
    margin: 0,
    fontSize: '26px',
    fontWeight: 800,
    color: 'var(--text-primary)',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  subtitle: {
    margin: '6px 0 0',
    fontSize: '14px',
    color: 'var(--text-secondary)',
  },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '24px',
    backgroundColor: 'transparent',
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--text-secondary)',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  primaryBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '11px 22px',
    borderRadius: '10px',
    backgroundColor: 'var(--accent-primary)',
    color: '#FFF',
    fontWeight: 600,
    fontSize: '14px',
    border: 'none',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  searchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: '12px',
    padding: '0 16px',
    height: '48px',
    width: '350px',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    fontSize: '14px',
    flex: 1,
    backgroundColor: 'transparent',
    color: 'var(--text-primary)',
  },
  subTabsBar: {
    display: 'flex',
    gap: '32px',
    borderBottom: '1px solid var(--border)',
    marginBottom: '32px',
    flexWrap: 'wrap',
  },
  subTabBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 0',
    backgroundColor: 'transparent',
    fontSize: '15px',
    fontWeight: 700,
    cursor: 'pointer',
    border: 'none',
    borderBottom: '2px solid transparent',
    color: 'var(--text-secondary)',
    marginBottom: '-1px',
  },
  subTabBtnActive: {
    borderBottom: '2px solid var(--accent-primary)',
    color: 'var(--text-primary)',
  },
  emptyState: {
    textAlign: 'center',
    padding: '80px 20px',
    color: 'var(--text-secondary)',
  },
  loadingWrap: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '400px',
  },
};